### ISSUE TITLE
[KDiZD] ToDo List for the upcoming KDiZD remaster

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#32]
For the upcoming remaster of KDiZD, I have various plans, that I have in my mind and that I need to write down somewhere to avoid forgetting them again. Here is the list, that will be updated from time to time.

**General changes in the resource department**

- [ ]     Instead of item rotation sprites, use voxels ( source 1 | source 2 )
- [ ]     Retexture the complete INTERMAP to make it look more like it's 2d graphic ideal
- [ ]     Include dynamic lights and brightmaps for all actors (original Doom/Doom2 material is already done and included)
- [ ]     Include brightmaps for all textures (original Doom/Doom2 material is already done and included)
- [ ]     Replace the "Chainsaw Zombie" with a better sprite set
- [ ]     Add scientist zombies and worker zombies (additional melee enemy for appropriate places)
- [ ]     Use original D2 sounds for Hell Knight
- [ ]     Add original sounds for Hell Warrior (grawl)
- [ ]     Make all the graphics widescreen compatible
- [ ]     Add a new PLAYPAL (similar to the one used in "The Refinery" for a generally darker look, adjust the resources to this look
- [ ]     Reconsider the monster rooster (remove the Mauler, Nightmare, Hell's Fury and StoneImp, add more fitting replacements)
- [ ]     Add new sprites for chainsaw zombie and Magmantis (Nash, paid)
- [ ]     Re-Add monster infighting (make sure to add species to imps)
- [ ]     Change shading for dark imps to make them look like evolution versions of normal imps (from grey to dark brown)
- [ ]     Readd the super shotgun sprites from Doom 2
- [ ]     Replace the forcefield textures (animated) by a better style forcefield that moves seamless
- [ ]     Replace the old music files with new tunes (by Andrej Avkhimovich)
- [ ]     Make some props destroyable (just for entertainment purpose ala Duke 3D)
- [ ]     Incorporate new effect designs (from other Remasters or even from Blade of Agony)

**Map changes**

- [ ]     Instead of complicated sector lights, we use dynamic lights (normal and spotlights)
- [ ]     Reduce backtracking in all the maps to a minimum and improve map routes to be less search-intensive
- [ ]     Add a storyline and a way to tell the story by placing some kind of readable pda's around the maps
- [ ]     Reduce the key-hunt by adding mission objectives (similar to Z1M1 where you place a bomb at a wall to proceed)
- [ ]     Replace software portals and fake floor hackyness with real portals
- [ ]     Make the skyboxes more convincing (better clouds, better weather effects)
- [ ]     Add colored lighting and fog to places that benefit from such an addition (this will be true-color based, not software limited)
- [ ]     Replace all light gradient textures by actors (similar to Sapphire and Austerity) for a more modern look.
- [ ]     Replace light glow sprites with new design (similar to Sapphire and Austerity as above)
- [ ]     Improve terrain/rock textures and make it look more modern (less tiling)
- [ ]     Normalize the mapping style throughout the whole episode to make it feel more connected and seamless
- [ ]
