### ISSUE TITLE
[TheRefinery] List of "to-do"s before finalization

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#44]
- [x] Add different see and death sounds to the blop
- [x] Add a sprite-based rocket trail to the rocket "in-air"
- [x] Improve steam sprite effects (BoA-style with better sprites and rotation effect, maybe @Ozymandias81 you can help here)
- [x] Add new sound for steam
- [x] Improve special effect fire (BoA style fire, maybe you can help here as well @Ozymandias81 )

**Comment by RichardDS90** [comment]
The Blot recently got updated on Realm667 maybe we could use one?

**Comment by Tormentor667** [comment]
What was changed there?

**Comment by RichardDS90** [comment]
New sprites, new sounds and improved behavior, do you want me to implement it?

**Comment by Tormentor667** [comment]
Sounds like an improvement, let’s go for it

**Comment by RichardDS90** [comment]
As for the rocket trail part, isn't it already a part of ZDoom?

**Comment by Tormentor667** [comment]
I'd create something more modern and individual instead of the built in solution.

**Comment by RichardDS90** [comment]
I might have a crack at the rocket trail, is it specifically the particle sprite part + sprite that needs replacing?

**Comment by Tormentor667** [comment]
Done with the improvements so far. I posted the RC1 at ZDoom.org - let's see what feedback we do get :) Thanks a lot @RichardDS90 I owe you one! https://forum.zdoom.org/viewtopic.php?f=19&t=74196
